# Generated by Django 5.2.8 on 2026-06-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementupload',
            name='preview_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statementupload',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statementupload',
            name='row_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
