# Generated by Django 5.2.8 on 2026-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_statementupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementupload',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
